language: java

notifications:  
  slack: 
    rooms: 
      secure: EP8sGePqGZuuR3Dg+ADOeIcSdZPi+gW8nQ20H7ddNJr6gbTQqqYDDJAdV3KzSwpXgzvNAm/f2Nf6QvII6LmGW8szlDnNZ5KOuQYhSP3K7yQJC1aO816YvnEHyZW4LCCTGMo+olmQFHbXhAgrZs7bLxGYpbXAbo5NBC3SG/vcEb2vk5SXL64zZjBQD4RML/e385a31zGMGgJJfMDsP/EUHsBBSj8rkyKbQH5LgPJJylbhBgbEzcbt0emZxIeNW1GmDpHJ+VqLm+XiVKLixZ3vCNtWxDrorxdQc0Lc+ZESz08wgGkHYm2y0FCtZJZ5RkU4K1gAEtltHfBviXsu0QfB+Wmez8jTdcf3uM3c0CXkCZfH+M8SvK/vV5QtFahjWCnv0ddchNRrDJ7cCsJIW2JoGGgJZWwdPj3zrGcgp8ZSAgU/QXoKpJufnbbBNuIfC5OuKie4Al2HMFoi7VKBrbYJWJCMmPy5TTQWLZqGF1YWuSxKz8olc3d7FUaKSCEHhdFB6VXPjIPkbZyNb+6hnbf3Tx8B9SgbLtFczb+kIOveC4DF3DUgwMSEoh7Oh+cgw3O7o/gj4J7hIJCWnDkS5ymtBoROBtoeCOm0uIZy+X7wb+LEobudRhS5LVlUrJCuPGyphM2rcJB/Yji4dBiRKTw3YC4SqN70QZq/clUMSKIk8Z4=
    on_success: always
    on_failure: always

os:
  - linux

branches:
  only:
    - master

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - |
      if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then
        JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
        ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
      fi
script:
  - ./gradlew clean
  - ./gradlew build
