
service: java-lambda-account

provider:
  name: aws
  runtime: java8
  profile: ${env:PROFILE, 'uvsy-sls-dev'}
  stage: ${opt:stage, 'dev'}
  region: ${env:REGION, 'sa-east-1'}
  deploymentBucket: ${self:provider.stage}.${self:provider.region}.universy.serverless.deploys
  deploymentPrefix: ${self:provider.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cognito-idp:InitiateAuth"
        - "cognito-idp:SignUp"
        - "cognito-idp:ConfirmSignUp"
        - "cognito-idp:ResendConfirmationCode"
      Resource: "*"
  environment:
    STAGE: ${self:provider.stage}
    CLIENT_ID: ${ssm:/${self:provider.stage}/cognito/clients/universy_mobile_client_id~true}
    AWS_COGNITO_REGION: ${ssm:/${self:provider.stage}/cognito/region~true}

package:
  artifact: build/distributions/${self:service}-1.0.zip

functions:
  handler:
    name: ${self:provider.stage}-${self:service}
    handler: app.universy.account.Handler
