Resources:
  logOn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/run
      Handler: com.universy.auth.LogOnHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          AWS_REGION: sa-east-1

  logIn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/run
      Handler: com.universy.auth.LogInHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          AWS_REGION: sa-east-1

