Resources:
  logOnPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/run
      Handler: com.universy.account.handler.logon.LogOnPostHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          AWS_COGNITO_REGION: us-east-1
          CLIENT_ID: 4rdnacs24atdg84gkjs63g3f21

  verifyPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/run
      Handler: com.universy.account.handler.verify.VerifyPostHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          AWS_COGNITO_REGION: us-east-1
          CLIENT_ID: 4rdnacs24atdg84gkjs63g3f21

  verifyGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/run
      Handler: com.universy.account.handler.verify.VerifyGetHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          AWS_COGNITO_REGION: us-east-1
          CLIENT_ID: 4rdnacs24atdg84gkjs63g3f21

  logInPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/run
      Handler: com.universy.account.handler.login.LogInPostHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          AWS_REGION: sa-east-1
          AWS_COGNITO_REGION: us-east-1
          CLIENT_ID: 4rdnacs24atdg84gkjs63g3f21